### ISSUE TITLE
Is there any limitations?

### ISSUE THREAD

**Issue by marcfrancislargo** [jsonstorage/docs#1]
I'd like to incorporate this into my app to store user information such as profile picture urls and other details. I'm afraid I'll reach a point where this will not work anymore due to limitations. Right now, my app has 5k users.

**Comment by adoprog** [comment]
As long as the JSON object size is <100kb and you're satisfied with current API performance, you should not face any limitations.
Note, that currently the API does not support partial updates, i.e. you'd have to send along the entire JSON object even during PUT requests.

**Comment by harshtiwari47** [comment]
How to update data ? No documents found please solve link error

**Comment by jsonstorage** [comment]
PUT /v1/json/(userId)/(itemId) Server response: 200 OK - Your JSON data returned.
