### ISSUE TITLE
Unauthorized API does not work

### ISSUE THREAD

**Issue by ebarra** [jsonstorage/docs#4]
When I try the following code it gives me 400 bad request response.
try {
                const myjsonurl = "https://api.jsonstorage.net/v1/json";
                const res = await fetch(myjsonurl, {
                  method: 'POST', 
                  headers:{
                      "Content-Type": "application/json; charset=UTF-8",
                  },
                  body: JSON.stringify(content)
                });
                const {uri} = await res.json();
                return uri;               
            } catch (err) {
                console.log(err);
            }

If I change the const myjsonurl for (the one in the MVC example):
                const myjsonurl = "https://api.jsonstorage.net/v1/json?apiKey=8969a471-87b7-4758-9f34-b090d396d9bb&name=jsfiddle-" + new Date().toISOString();
 
It works.
Can you check if I am doing something wrong or if something is missing in the docs.

Thanks in advance

**Comment by ebarra** [comment]
JSFiddle with the demo failing with Bad Request: https://jsfiddle.net/Lz9sp630/4/

**Comment by adoprog** [comment]
Where did you find the link to JSFiddle? The website (https://www.jsonstorage.net/) has new link in it.

**Comment by ebarra** [comment]
I created it based on your jsfiddle (https://jsfiddle.net/adoprog/s4tue5g6/) just replacing the URL removing the api_key. As far as I understand the unauthenticated API is like that and should work, shouldn´t it?

**Comment by ebarra** [comment]
Thank you.
I was planning to use it in a MOOC at UPM, but I will ask the students to register to get an api_key
Thank you very much

**Comment by adoprog** [comment]
You're welcome!
