### ISSUE TITLE
Receive apiKey through a secure header

### ISSUE THREAD

**Issue by mtsbarbosa** [jsonstorage/docs#6]
Hi, I'd like to point that passing the apiKey through the url might not be too safe, maybe its a good idea to receive it optionally by a safe header instead. What do you think?

**Comment by jsonstorage** [comment]
If using HTTPS if it completely safe to pass query string arguments, but it is a good point in general, we will look into it. Thank you!

**Comment by jsonstorage** [comment]
@mtsbarbosa Done, added 'x-api-key' header support - it is used if no apiKey query string provided.
